backup_dev_version/routes/web.php
<?php
use Illuminate\Http\Request;
use App\Http\Middleware\Supplier;
use App\Models\Ecommerce\Product;



Route::post('app/ipaymu/notify/cod', 'Ecommerce\SettingController@ipaymuNotify')->name('notify');

Route::post('/ipaymu/notify', 'Store\StoreController@ipaymu');

Route::get('app/api/zipcode', 'Ecommerce\SettingController@getZipCode')->name('app.setting.zipcode');
Route::group(['domain' => 'seller.refeed.co.id', 'namespace' => 'Seller'], function () {
    Route::group(['prefix' => '{seller}'], function () {
        Route::get('/', 'StoreController@index')->name('store');
        Route::get('/product', 'ProductController@index')->name('product');
        Route::get('/product/{slug}', 'ProductController@show')->name('product.show');
        Route::post('/cart', 'CartController@store')->name('cart.store');
        Route::get('/cart', 'CartController@index')->name('cart.index');
        Route::get('/checkout', 'CheckoutController@index')->name('checkout.index');
    });
});

Route::get('totalMembers', function () {
    $total = \App\Models\Ecommerce\Store::count();
    return response()->json(['Members' => $total]);
});

Route::get('/digital/{id}', 'Store\CartController@download')->name('digital');

Route::post('/winpay/payment', 'Store\CartController@notify_winpay');
Route::get('/cron-notify/{id}', 'Store\CartController@cron')->name('cron-notify');

Route::get('/events/{event_id}', 'Events\Event@index');
Route::post('/events/checklimit', 'Events\Event@limitingUsers');
Route::post('/events/create', 'Auth\RegisterController@createPromo');

Route::get('/aws', 'AwsController@index');
Route::post('register-reseller-post', 'ResellerController@register_process')->name('register-reseller-post');
// Route::get('register-reseller', 'ResellerController@register')->name('register-reseller');


//reseller = dropship
//reseller new= reseller

Route::get('register-dropshipper', 'ResellerController@registerDropshipper')->name('register-dropshipper');

Route::post('login-reseller-post', 'ResellerController@login_process')->name('login-reseller-post');
Route::get('login-reseller', 'Auth\AuthController@showLoginReseller')->name('login-reseller');
Route::get('reseller-activation', 'ResellerController@activation')->name('reseller.activation');
Route::post('logout-reseller', 'ResellerController@logout')->name('logout-reseller');
Route::post('reseller/add-cart', 'Reseller\CartController@create');
Route::group(['as' => 'reseller.', 'prefix' => 'dropship', 'namespace' => 'Reseller'], function () {
    Route::group(['middleware' => ['reseller']], function () {
        Route::get('/', 'AppController@index')->name('dashboard');
        Route::post('/setting', 'SettingController@update')->name('setting.update');
        Route::get('/setting', 'SettingController@index')->name('setting');
        Route::get('/panduan', 'DocController@index')->name('panduan');
        Route::get('/pengumuman', 'DocController@pengumuman')->name('pengumuman');
        Route::get('/rule', 'DocController@rule')->name('rule');
        Route::get('/reward', 'DocController@reward')->name('reward');
        Route::get('/faq', 'DocController@faq')->name('faq');
        Route::get('/product', 'ProductController@index')->name('product');
        Route::get('/product/{id}', 'ProductController@show')->name('product.show');
        Route::get('/sales', 'OrderController@index')->name('sales');
        Route::get('/sales/edit/{id}', 'OrderController@edit')->name('sales.edit');

        Route::get('/cart/{session}', 'CartController@index')->name('cart');
        Route::post('/cart/store', 'CartController@store')->name('cart.store');
        Route::post('/delete-cart/{id}', 'CartController@destroy')->name('delete-cart');
        Route::get('/payment/{id}', 'CartController@payment')->name('payment');
    });
});

Route::get('login-warehouse', 'Warehouse\LoginController@login')->name('login-warehouse');
Route::post('login-warehouse', 'Warehouse\LoginController@login_process')->name('login-warehouse-post');

Route::group(['as' => 'warehouse.', 'prefix' => 'warehouse', 'namespace' => 'Warehouse'], function () {
    Route::group(['middleware' => ['warehouse']], function () {
        Route::get('/', 'AppController@index')->name('dashboard');
        
        Route::get('/sales', 'SalesController@index')->name('sales.index');
        Route::get('/sales/edit/{id}', 'SalesController@edit')->name('sales.edit');
        Route::get('/sales/{id}', 'SalesController@show')->name('sales.show');
        Route::post('/sales/update/{id}', 'SalesController@update')->name('sales.update');
        Route::get('/sales/search', 'SalesController@search')->name('sales.search');
        Route::get('/sales/export', 'SalesController@export')->name('sales.export');
        
        Route::get('/stock', 'StockController@index')->name('stock.index');
        Route::post('/stock/update', 'StockController@update')->name('stock.update');
        
        Route::post('logout', 'LoginController@logout')->name('logout');
    });
});


Route::group(['as' => 'affiliasi.', 'prefix' => 'affiliasi', 'namespace' => 'Affiliasi'], function () {

    Route::get('login', 'AccountController@login')->name('login');
    Route::get('/register', 'AccountController@register')->name('register');
    Route::post('register-process', 'AccountController@register_process')->name('register-process');
    Route::post('login', 'AccountController@login_process')->name('login-process');
    Route::get('activation', 'AccountController@activation')->name('activation');
    Route::post('logout', 'AccountController@logout')->name('logout');

    Route::group(['middleware' => ['affiliasi']], function () {
        Route::get('/', 'AppController@index')->name('dashboard');
        // Route::post('/setting','SettingController@update')->name('setting.update');
        // Route::get('/setting', 'SettingController@index')->name('setting');
        // Route::get('/panduan', 'DocController@index')->name('panduan');

        Route::resource('/user', 'UserController', ['names' => 'user']);
        Route::resource('/product', 'ProductController', ['names' => 'product']);
        Route::resource('/fee', 'FeeController', ['names' => 'fee']);
    });
});

Route::group(['domain' => '{subdomain}.refeed.id', 'where' => ['subdomain' => '(?!\\bwww\\b)[0-9A-Za-z\-\_]+']], function () {

    Route::get('login-dropshipper', 'ResellerController@login_dropshipper')->name('login-dropshipper');

    Route::get('register-reseller','ResellerReal\AccountController@register')->name('register.reseller');

    // Route::get('/', 'Store\StoreController@index')->name('store');
    Route::get('/', 'Store\StoreController@indexNew')->name('store');
    Route::get('/beranda', 'Store\StoreController@index')->name('store.beranda');

    Route::get('/product', 'Store\StoreController@product')->name('product');
    Route::get('/product/{slug}', 'Store\StoreController@detailProduct')->name('item');
    Route::get('/cart/{session}', 'Store\CartController@index')->name('cart');
    Route::get('/success/{id}', 'Store\StoreController@success')->name('success');
    Route::post('/notify/{id}', 'Store\StoreController@notify')->name('notify');
    Route::get('/check-transaction', 'Store\StoreController@checkTransaction')->name('checktrx');
    Route::get('/search', 'Store\StoreController@search')->name('search');
    Route::get('/category/{id}', 'Store\StoreController@getCategory')->name('category');
    Route::get('/note', 'Store\StoreController@note')->name('note');

    Route::post('/add-cart', 'Store\CartController@create');
    Route::get('/add-cart123', 'Store\CartController@create');
    Route::post('/delete-cart/{id}', 'Store\CartController@destroy')->name('delete-cart');
    Route::post('/add-order', 'Store\CartController@add_order')->name('add-order');
    Route::post('/add-orderReseller', 'Ecommerce\ResellerReal@add_order')->name('add-orderReseller');

    Route::post('/check', 'Store\StoreController@getcheckTransaction')->name('checkTransaction');
    Route::post('/check-coupon', 'Store\StoreController@checkCoupon')->name('check-coupon');

    Route::get('/toolbar', 'Store\CartController@toolbar')->name('toolbar');
    Route::get('/token', 'Store\CartController@token')->name('token');
    Route::get('/payment', 'Store\CartController@payment')->name('payment');
    Route::get('/payment1', 'Store\CartController@payment1')->name('payment1');
    Route::get('/awb', 'Store\StoreController@awb')->name('awb');

    Route::post('/visitor', 'Store\StoreVisitorController@visitor')->name('visitor');
    Route::get('/page/{id}', 'Store\StoreController@page')->name('page');
    
    Route::post('/create-testimoni', 'Store\StoreController@testimoniCreate')->name('create.testimoni');
    Route::get('/create-testimoni', 'Store\StoreController@testimoniForm')->name('create.testimoni');
    Route::get('/testimoni', 'Store\StoreController@testimoni')->name('testimoni');
    Route::get('/vidio', 'Store\StoreController@vidio')->name('vidio');
});

Route::group(['domain' => '{subdomain}.id', 'where' => ['subdomain' => '(?!\\bwww\\b)[0-9A-Za-z\-\_]+']], function () {

    Route::get('login-dropshipper', 'ResellerController@login_dropshipper')->name('login-dropshipper');

    // Route::get('/', 'Store\StoreController@index')->name('store');
    Route::get('/', 'Store\StoreController@indexNew')->name('store');
    Route::get('/beranda', 'Store\StoreController@index')->name('store.beranda');

    Route::get('/product', 'Store\StoreController@product')->name('product');
    Route::get('/product/{slug}', 'Store\StoreController@detailProduct')->name('item');
    Route::get('/cart/{session}', 'Store\CartController@index')->name('cart');
    Route::get('/success/{id}', 'Store\StoreController@success')->name('success');
    Route::post('/notify/{id}', 'Store\StoreController@notify')->name('notify');
    Route::get('/check-transaction', 'Store\StoreController@checkTransaction')->name('checktrx');

backup_dev_version/app/Http/Controllers/Ecommerce/ResellerController.php
<?php

namespace App\Http\Controllers\Ecommerce;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Reseller;
use App\Models\Order;
use Auth;
class ResellerController extends Controller
{
    public function index()
    { 
        $models = Reseller::where('store_id', Auth::user()->store->id)->paginate(10);
        $data = Order::where('reseller_id', '!=', '0')->where('store_id', Auth::user()->store->id)->where('status', '!=', Order::STATUS_CANCEL)->where('status', '!=', Order::STATUS_WAITING_PAYMENT)->orderBy('created_at', "DESC")->paginate(20);
        
        return view('backend.reseller.index', compact('models', 'data'));
    }

    public function dropship()
    { 
        $user=Auth::user();
        
        $models = Reseller::where('store_id', Auth::user()->store->id)->paginate(10);
        $data = Order::where('reseller_id', '!=', '0')->where('store_id', Auth::user()->store->id)->where('status', '!=', Order::STATUS_CANCEL)->where('status', '!=', Order::STATUS_WAITING_PAYMENT)->orderBy('created_at', "DESC")->paginate(20);
        
        $titleText=$user->getMeta('titleDropship')['meta_value'];
        $desc=$user->getMeta('deskripsiDropship')['meta_value'];

        
        return view('backend.reseller.index', compact('models', 'data','titleText','desc'));
    }

    public function show($id)
    {
        $data = Order::where('reseller_id', $id)->where('store_id', Auth::user()->store->id)->where('status', '!=', Order::STATUS_CANCEL)->where('status', '!=', Order::STATUS_WAITING_PAYMENT)->orderBy('created_at', "DESC")->paginate(20);
        return view('backend.reseller.detail', compact('data'));  
    }
    public function verify($id)
    {
        $data = Reseller::findOrFail($id);
        $status = 1;
        if(\Request::get('status') == 0){
            $status = 0;
        }
        $data->verify = $status;
        $data->save();

        $models = Reseller::where('store_id', Auth::user()->store->id)->paginate(10);
        $data = Order::where('reseller_id', '!=', '0')->where('store_id', Auth::user()->store->id)->where('status', '!=', Order::STATUS_CANCEL)->where('status', '!=', Order::STATUS_WAITING_PAYMENT)->orderBy('created_at', "DESC")->paginate(20);
        return redirect()->back();
        // return view('backend.reseller.detail', compact('data'));  
    }
}

backup_dev_version/app/Http/Controllers/Reseller/AppController.php
<?php

namespace App\Http\Controllers\Reseller;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use App\Models\Order;
use Carbon;
class AppController extends Controller
{
    
    public function index()
    {
        $data = Auth::guard('resellers')->user()->store;
        $sales      = Order::where('store_id', $data->id)
                        ->whereDate('created_at', Carbon::now()->format('Y-m-d'))
                        ->where('status', '!=', Order::STATUS_CANCEL)
                        ->where('status', '!=', Order::STATUS_WAITING_PAYMENT)
                        ->where('reseller_id', Auth::guard('resellers')->user()->id)
                        ->sum('total');
        $trx_waiting      = Order::where('store_id',  $data->id)
                        ->whereMonth('created_at', Carbon::now()->month)
                        ->where('status', '!=', Order::STATUS_CANCEL)
                        ->where('status', '!=', Order::STATUS_WAITING_PAYMENT)
                        ->where('reseller_id', Auth::guard('resellers')->user()->id)
                        ->sum('total');
        // $trx_waiting  = Order::where('store_id', Auth::user()->store->id)->where('status','0')->whereMonth('created_at', Carbon::now()->month)->count();
        $trx_total  = Order::where('store_id', $data->id)->where('reseller_id', Auth::guard('resellers')->user()->id)->whereMonth('created_at', Carbon::now()->month)->count();
        
        $sdate = DATE('Y-m-d', strtotime(DATE('Y-m-d')."-6 day"));
        for ($i=0; $i < 7; $i++) { 
            $ndate = DATE('Y-m-d', strtotime($sdate."+".$i." day"));
            $sidate = DATE('d-m-Y', strtotime($sdate."+".$i." day"));
            $date_graph[]   = $sidate;

            $amount_graph[] = Order::where('store_id', $data->id)
            ->whereDate('created_at', $ndate)
            ->where('status', '!=', Order::STATUS_CANCEL)
            ->where('status', '!=', Order::STATUS_WAITING_PAYMENT)
            ->where('reseller_id', Auth::guard('resellers')->user()->id)
            ->sum('total');

            $data_per_bulan = Order::where('store_id', $data->id)
            ->whereDate('created_at', $ndate)
            ->where('status', '!=', Order::STATUS_CANCEL)
            ->where('status', '!=', Order::STATUS_WAITING_PAYMENT)
            ->where('reseller_id', Auth::guard('resellers')->user()->id)
            ->get();

            $total_bonus = 0;
            foreach($data_per_bulan as $item){
                foreach($item->detail as $bonus){
                    if($bonus->reseller_unit == 'harga') {
                        $total_bonus += $bonus->reseller_value*$bonus->qty;
                    }else{
                        $total_bonus += $bonus->total*$bonus->reseller_value/100;
                    }
                }
            }

            $amount_graph_bonus[] = $total_bonus; 

                                                   
        }
        $date_graph =json_encode($date_graph);
        $amount_graph =json_encode($amount_graph);
        $amount_graph_bonus =json_encode($amount_graph_bonus);

        
        $models = Order::where('store_id', $data->id)->where('reseller_id', Auth::guard('resellers')->user()->id)->orderBy('id', 'desc')->paginate(10);

        return view('reseller.home', compact('models', 'amount_graph', 'amount_graph_bonus', 'date_graph', 'data', 'trx_total', 'trx_waiting', 'sales'));
    }
}

backup_dev_version/app/Http/Controllers/Reseller/DocController.php
<?php

namespace App\Http\Controllers\Reseller;

use App\Http\Controllers\Controller;
use App\Models\Guide;
use Illuminate\Http\Request;
use Auth;
use App\Models\Ecommerce\Store;
use App\Models\StoreFaq;

class DocController extends Controller
{
    public function index()
    {
        $me=Auth::guard('resellers')->user();
        
        // $models = Guide::where('target', 'DROPSHIPPER')->whereIn("store_id",$me->store_id)->get();
        $models = Guide::where('target', 'DROPSHIPPER')
            ->where(function ($query) {
                $query->where('store_id',Auth::guard('resellers')->user()->store_id)
                    ->orWhereNull('store_id');
            }
        )->get();
        return view('reseller.panduan.index', compact('models'));
    }
    public function pengumuman()
    {
        $models = Guide::where('target', 'SR')->where('store_id', Auth::guard('resellers')->user()->store->id)->orderBy('id', 'desc')->get();
        return view('reseller.pengumuman.index', compact('models'));
    }
    public function rule()
    {
        $models =  Store::findOrFail(Auth::guard('resellers')->user()->store->id);
        return view('reseller.pengumuman.rule', compact('models'));
    }
    public function reward()
    {
        $models =  Store::findOrFail(Auth::guard('resellers')->user()->store->id);
        return view('reseller.pengumuman.reward', compact('models'));
    }
    public function faq()
    {
        $models =  Store::findOrFail(Auth::guard('resellers')->user()->store->id);
        $datas = StoreFaq::where('status', '=', 1)
                    ->where('store_id', '=', Auth::guard('resellers')->user()->store->id)
                    ->where('category', '=', 'dropship')
                    ->get();
        return view('reseller.pengumuman.faq', compact('models', 'datas'));
    }
}

backup_dev_version/resources/views/reseller/layouts/app.blade.php
<!doctype html>

<html lang="{{ app()->getLocale() }}">

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1">



    <title>@yield('page-title')</title>



    <link rel="stylesheet" href="/apps/css/normalize.css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <link rel="stylesheet" href="/apps/css/font-awesome.min.css">

    <link rel="stylesheet" href="/apps/css/themify-icons.css">

    <link rel="stylesheet" href="/apps/css/flag-icon.min.css">

    <link rel="stylesheet" href="/apps/css/cs-skin-elastic.css">

    <!-- <link rel="stylesheet" href="assets/css/bootstrap-select.less"> -->

    <link rel="stylesheet" href="/apps/scss/style.css">
    
    <link rel="shortcut icon" href="/landing/img/icon.png" type="image/x-icon">
    <link href="/apps/css/custom.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

    <style type="text/css">

    	html, body {

            max-width: 100%;

            overflow-x: hidden;

        }

        @media screen and (max-width:580px){

            .navbar .navbar-brand img{

                width: 100px;

            }

        }

    </style>



    @stack('head')



</head>

<body>

	        <!-- Left Panel -->


    <aside id="left-panel" class="left-panel">

        <nav class="navbar navbar-expand-sm navbar-default">



            <div class="navbar-header">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">

                    <i class="fa fa-bars"></i>

                </button>

                <a class="navbar-brand" href="{{route('app.dashboard')}}"><img src="https://refeed.id/landing/img/refeed-logo.png?ver=1.2" style="filter: brightness(0) invert(1);" alt="Refeed"></a>

                <a class="navbar-brand hidden" href="{{route('app.dashboard')}}"><img src="https://refeed.id/landing/img/logo-chats.png?ver=1.2" alt="Refeed"></a>


            </div>



            <div id="main-menu" class="main-menu collapse navbar-collapse">

                
                   
                <ul class="nav navbar-nav">

                    <div class="user-details">

                        <div class="pull-left">

                            <img src="" alt="">

                        </div>

                        <div class="user-info">

                            <div class="dropdown">

                                <a href="#">Hi, {{Auth::guard('resellers')->user()->name}}</a>

                            </div>

                        </div>

                    </div>

                    <h3 class="menu-title">Navigation</h3>

                  

                    

                   
                        <li>

                            <a href="{{route('reseller.dashboard')}}" > <i class="menu-icon fa fa-dashboard"></i>Dashboard</a>

                        </li>
                        <li>

                                <a href="{{route('reseller.product')}}" > <i class="menu-icon fa fa-list-alt"></i>Produk</a>
    
                            </li>
                        @if(Auth::guard('resellers')->user()->store->custom != 0)
                        <li>
                            @php $cart = DB::table('carts')->where('session',\Request::session()->getId())->get(); @endphp
                            <a href="{{route('reseller.cart',['id'=>\Request::session()->getId()])}}" > <i class="menu-icon fa fa-shopping-cart"></i>Keranjang Belanja
                                @if(count($cart)!=0)
                                @php $carts = 0; @endphp
                                    @foreach($cart as $cart)
                                    <?php $carts += $cart->qty; ?>
                                    @endforeach
                                <span class="notif-cart badge badge-light">{{ $carts }}<span>
                                @endif
                            </a>

                        </li>
                        @endif
                        <li>

                            <a href="{{route('reseller.sales')}}" > <i class="menu-icon fa fa-gift"></i>Bonus</a>

                        </li>
                         <li>

                            <a href="{{route('reseller.setting')}}" > <i class="menu-icon fa fa-gear"></i>Pengaturan</a>

                        </li>
                        <li>

                            <a href="{{route('reseller.panduan')}}" > <i class="menu-icon fa fa-book"></i>Panduan</a>

                        </li>
                        <li>

                                <a href="{{route('reseller.pengumuman')}}" > <i class="menu-icon fa fa-map"></i>Pengumuman</a>
    
                        </li>
                        
                        <li>
                            <a href="{{route('reseller.rule')}}" > <i class="menu-icon fa fa-file"></i>Aturan Dropship</a>
                        </li>
                        
                        <li>
                            <a href="{{route('reseller.reward')}}" > <i class="menu-icon fa fa-star"></i>Reward</a>
                        </li>
                        
                        <li>
                            <a href="{{route('reseller.faq')}}" > <i class="menu-icon fa fa-question-circle"></i>FAQ</a>
                        </li>
                        {{-- <li>

                            <a href="/register-reseller" > <i class="menu-icon fa fa-star"></i>Upgrade ke Reseller</a>

                        </li> --}}
                        
                                              

                </ul>

            </div><!-- /.navbar-collapse -->

        </nav>

    </aside><!-- /#left-panel -->



    <!-- Left Panel -->



    <!-- Right Panel -->

    <div id="right-panel" class="right-panel">



        <!-- Header-->

        <header id="header" class="header">



            <div class="header-menu">



                <div class="col-sm-7">

                    <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>

                </div>



                <div class="col-sm-5">

                    <div class="user-area dropdown float-right">

                        <a style="color:#ffffff;" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                             {{Auth::guard('resellers')->user()->name}} &nbsp;<i class="fa fa-angle-down"></i>

                        </a>



                        <div class="user-menu dropdown-menu">

                                {{--  <a class="nav-link" href="#"><i class="fa fa-user"></i> Lihat Semua Bot</a>

                                <a class="nav-link" href="#"><i class="fa fa-user"></i> Tambah Bot Baru</a>

                                <hr>

                                <a class="nav-link" href="#"><i class="fa fa-user"></i> Billing & Plan</a>

                                <hr>  --}}

                                <a class="nav-link" href="{{ route('reseller.setting') }}"><i class="fa fa-cog"></i> Pengaturan Akun</a>
                                {{--  <a class="nav-link" href="{{ route('app.billing') }}"><i class="fa fa-money"></i> Billing Akun</a>  --}}

                                <a class="nav-link" onclick="event.preventDefault();

                                                     document.getElementById('logout-form').submit();">

                                        <i class="fa fa-power-off"></i> {{ __('Logout') }}</a>

                                <form id="logout-form" action="{{ route('logout-reseller') }}" method="POST" style="display: none;">

                                        @csrf

                                    </form>

                        </div>

                    </div>



                </div>

            </div>



        </header><!-- /header -->

       
	@yield('content')
        
	<!-- Right Panel -->

	

	@include('reseller.layouts.main_js')



    @stack('scripts')

	

</body>

</html>

backup_dev_version/resources/views/reseller/layouts/head.blade.php
	<link rel="stylesheet" href="backend/assets/css/normalize.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="backend/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="backend/assets/css/themify-icons.css">
    <link rel="stylesheet" href="backend/assets/css/flag-icon.min.css">
    <link rel="stylesheet" href="backend/assets/css/cs-skin-elastic.css">
    <!-- <link rel="stylesheet" href="assets/css/bootstrap-select.less"> -->
    <link rel="stylesheet" href="backend/assets/scss/style.css">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->

backup_dev_version/resources/views/reseller/layouts/main_js.blade.php
<script src="/apps/js/vendor/jquery-2.1.4.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

<!-- <script src="assets/js/vendor/jquery-2.1.4.min.js"></script> -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script> -->
<script src="/apps/js/plugins.js"></script>
<script src="/apps/js/main.js"></script>


<script src="/apps/js/lib/chart-js/Chart.bundle.js"></script>
<script src="/apps/js/dashboard.js"></script>
<script src="/apps/js/widgets.js"></script>
<script src="/apps/js/lib/vector-map/jquery.vmap.js"></script>
<script src="/apps/js/lib/vector-map/jquery.vmap.min.js"></script>
<script src="/apps/js/lib/vector-map/jquery.vmap.sampledata.js"></script>
<script src="/apps/js/lib/vector-map/country/jquery.vmap.world.js"></script>


<script type="text/javascript" src="/js/jquery.countdown.js"></script>