backup_dev_version/routes/web.php
    Route::group(['prefix' => '{seller}'], function () {
        Route::get('/', 'StoreController@index')->name('store');
        Route::get('/product', 'ProductController@index')->name('product');
        Route::get('/product/{slug}', 'ProductController@show')->name('product.show');
        Route::post('/cart', 'CartController@store')->name('cart.store');
        Route::get('/cart', 'CartController@index')->name('cart.index');
        Route::get('/checkout', 'CheckoutController@index')->name('checkout.index');
    });
});

Route::get('totalMembers', function () {
    $total = \App\Models\Ecommerce\Store::count();
    return response()->json(['Members' => $total]);
});

Route::get('/digital/{id}', 'Store\CartController@download')->name('digital');

Route::post('/winpay/payment', 'Store\CartController@notify_winpay');
Route::get('/cron-notify/{id}', 'Store\CartController@cron')->name('cron-notify');

Route::get('/events/{event_id}', 'Events\Event@index');
Route::post('/events/checklimit', 'Events\Event@limitingUsers');
Route::post('/events/create', 'Auth\RegisterController@createPromo');

Route::get('/aws', 'AwsController@index');
Route::post('register-reseller-post', 'ResellerController@register_process')->name('register-reseller-post');
// Route::get('register-reseller', 'ResellerController@register')->name('register-reseller');


//reseller = dropship
//reseller new= reseller

Route::get('register-dropshipper', 'ResellerController@registerDropshipper')->name('register-dropshipper');

Route::post('login-reseller-post', 'ResellerController@login_process')->name('login-reseller-post');
Route::get('login-reseller', 'Auth\AuthController@showLoginReseller')->name('login-reseller');
Route::get('reseller-activation', 'ResellerController@activation')->name('reseller.activation');
Route::post('logout-reseller', 'ResellerController@logout')->name('logout-reseller');
Route::post('reseller/add-cart', 'Reseller\CartController@create');
Route::group(['as' => 'reseller.', 'prefix' => 'dropship', 'namespace' => 'Reseller'], function () {
    Route::group(['middleware' => ['reseller']], function () {
        Route::get('/', 'AppController@index')->name('dashboard');
        Route::post('/setting', 'SettingController@update')->name('setting.update');
        Route::get('/setting', 'SettingController@index')->name('setting');
        Route::get('/panduan', 'DocController@index')->name('panduan');
        Route::get('/pengumuman', 'DocController@pengumuman')->name('pengumuman');
        Route::get('/rule', 'DocController@rule')->name('rule');
        Route::get('/reward', 'DocController@reward')->name('reward');
        Route::get('/faq', 'DocController@faq')->name('faq');
        Route::get('/product', 'ProductController@index')->name('product');
        Route::get('/product/{id}', 'ProductController@show')->name('product.show');
        Route::get('/sales', 'OrderController@index')->name('sales');
        Route::get('/sales/edit/{id}', 'OrderController@edit')->name('sales.edit');

        Route::get('/cart/{session}', 'CartController@index')->name('cart');
        Route::post('/cart/store', 'CartController@store')->name('cart.store');
        Route::post('/delete-cart/{id}', 'CartController@destroy')->name('delete-cart');
        Route::get('/payment/{id}', 'CartController@payment')->name('payment');
    });
});

Route::get('login-warehouse', 'Warehouse\LoginController@login')->name('login-warehouse');
Route::post('login-warehouse', 'Warehouse\LoginController@login_process')->name('login-warehouse-post');

Route::group(['as' => 'warehouse.', 'prefix' => 'warehouse', 'namespace' => 'Warehouse'], function () {
    Route::group(['middleware' => ['warehouse']], function () {
        Route::get('/', 'AppController@index')->name('dashboard');
        
        Route::get('/sales', 'SalesController@index')->name('sales.index');
        Route::get('/sales/edit/{id}', 'SalesController@edit')->name('sales.edit');
        Route::get('/sales/{id}', 'SalesController@show')->name('sales.show');
        Route::post('/sales/update/{id}', 'SalesController@update')->name('sales.update');
        Route::get('/sales/search', 'SalesController@search')->name('sales.search');
        Route::get('/sales/export', 'SalesController@export')->name('sales.export');
        
        Route::get('/stock', 'StockController@index')->name('stock.index');
        Route::post('/stock/update', 'StockController@update')->name('stock.update');
        
        Route::post('logout', 'LoginController@logout')->name('logout');
    });
});


Route::group(['as' => 'affiliasi.', 'prefix' => 'affiliasi', 'namespace' => 'Affiliasi'], function () {

    Route::get('login', 'AccountController@login')->name('login');
    Route::get('/register', 'AccountController@register')->name('register');
    Route::post('register-process', 'AccountController@register_process')->name('register-process');
    Route::post('login', 'AccountController@login_process')->name('login-process');
    Route::get('activation', 'AccountController@activation')->name('activation');
    Route::post('logout', 'AccountController@logout')->name('logout');

    Route::group(['middleware' => ['affiliasi']], function () {
        Route::get('/', 'AppController@index')->name('dashboard');
        // Route::post('/setting','SettingController@update')->name('setting.update');
        // Route::get('/setting', 'SettingController@index')->name('setting');
        // Route::get('/panduan', 'DocController@index')->name('panduan');

        Route::resource('/user', 'UserController', ['names' => 'user']);
        Route::resource('/product', 'ProductController', ['names' => 'product']);
        Route::resource('/fee', 'FeeController', ['names' => 'fee']);
    });
});

Route::group(['domain' => '{subdomain}.refeed.id', 'where' => ['subdomain' => '(?!\\bwww\\b)[0-9A-Za-z\-\_]+']], function () {

    Route::get('login-dropshipper', 'ResellerController@login_dropshipper')->name('login-dropshipper');

    Route::get('register-reseller','ResellerReal\AccountController@register')->name('register.reseller');

    // Route::get('/', 'Store\StoreController@index')->name('store');
    Route::get('/', 'Store\StoreController@indexNew')->name('store');
    Route::get('/beranda', 'Store\StoreController@index')->name('store.beranda');

    Route::get('/product', 'Store\StoreController@product')->name('product');
    Route::get('/product/{slug}', 'Store\StoreController@detailProduct')->name('item');
    Route::get('/cart/{session}', 'Store\CartController@index')->name('cart');
    Route::get('/success/{id}', 'Store\StoreController@success')->name('success');
    Route::post('/notify/{id}', 'Store\StoreController@notify')->name('notify');
    Route::get('/check-transaction', 'Store\StoreController@checkTransaction')->name('checktrx');
    Route::get('/search', 'Store\StoreController@search')->name('search');
    Route::get('/category/{id}', 'Store\StoreController@getCategory')->name('category');
    Route::get('/note', 'Store\StoreController@note')->name('note');

    Route::post('/add-cart', 'Store\CartController@create');
    Route::get('/add-cart123', 'Store\CartController@create');
    Route::post('/delete-cart/{id}', 'Store\CartController@destroy')->name('delete-cart');
    Route::post('/add-order', 'Store\CartController@add_order')->name('add-order');
    Route::post('/add-orderReseller', 'Ecommerce\ResellerReal@add_order')->name('add-orderReseller');

    Route::post('/check', 'Store\StoreController@getcheckTransaction')->name('checkTransaction');
    Route::post('/check-coupon', 'Store\StoreController@checkCoupon')->name('check-coupon');

    Route::get('/toolbar', 'Store\CartController@toolbar')->name('toolbar');
    Route::get('/token', 'Store\CartController@token')->name('token');
    Route::get('/payment', 'Store\CartController@payment')->name('payment');
    Route::get('/payment1', 'Store\CartController@payment1')->name('payment1');
    Route::get('/awb', 'Store\StoreController@awb')->name('awb');

    Route::post('/visitor', 'Store\StoreVisitorController@visitor')->name('visitor');
    Route::get('/page/{id}', 'Store\StoreController@page')->name('page');
    
    Route::post('/create-testimoni', 'Store\StoreController@testimoniCreate')->name('create.testimoni');
    Route::get('/create-testimoni', 'Store\StoreController@testimoniForm')->name('create.testimoni');
    Route::get('/testimoni', 'Store\StoreController@testimoni')->name('testimoni');
    Route::get('/vidio', 'Store\StoreController@vidio')->name('vidio');
});

Route::group(['domain' => '{subdomain}.id', 'where' => ['subdomain' => '(?!\\bwww\\b)[0-9A-Za-z\-\_]+']], function () {

    Route::get('login-dropshipper', 'ResellerController@login_dropshipper')->name('login-dropshipper');

    // Route::get('/', 'Store\StoreController@index')->name('store');
    Route::get('/', 'Store\StoreController@indexNew')->name('store');
    Route::get('/beranda', 'Store\StoreController@index')->name('store.beranda');

    Route::get('/product', 'Store\StoreController@product')->name('product');
    Route::get('/product/{slug}', 'Store\StoreController@detailProduct')->name('item');
    Route::get('/cart/{session}', 'Store\CartController@index')->name('cart');
    Route::get('/success/{id}', 'Store\StoreController@success')->name('success');
    Route::post('/notify/{id}', 'Store\StoreController@notify')->name('notify');
    Route::get('/check-transaction', 'Store\StoreController@checkTransaction')->name('checktrx');
    Route::get('/search', 'Store\StoreController@search')->name('search');
    Route::get('/category/{id}', 'Store\StoreController@getCategory')->name('category');
    Route::get('/note', 'Store\StoreController@note')->name('note');

    Route::post('/add-cart', 'Store\CartController@create');
    Route::get('/add-cart123', 'Store\CartController@create');
    Route::post('/delete-cart/{id}', 'Store\CartController@destroy')->name('delete-cart');

backup_dev_version/app/Http/Controllers/Ecommerce/WarehouseController.php
<?php

namespace App\Http\Controllers\Ecommerce;

use App\Warehouse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Validator;
use Illuminate\Support\Facades\Hash;

class WarehouseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $q              = \Request::get('q');

        $models         = Warehouse::where('store_id', Auth::user()->store->id)->when(
            $q, function ($query) use ($q) {
                            build_like_query($query, 'name', $q);
            }
        );

        $models = $models->where('status', '>=', 0);
        $status         = \Request::get('status');

        if($status != null) {
            $models = $models->where('status', $status);
        }

        $models = $models->paginate(10);

        return view('backend.warehouse.index', compact('models'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Warehouse();

        return view('backend.warehouse.form', compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator       = \Validator::make(
            $request->all(),
            [
                'name'       => 'required|string|regex:/^[0-9A-Za-z_ ]*$/',
                'phone'      => 'required|numeric',
                'email'      => 'required|email|unique:warehouse,email',
                'password'   => 'required|string|min:6|confirmed',
            ],
            [
                'confirmed' => ':attribute tidak cocok',
                'required'          => ':attribute tidak boleh kosong.',
                'email'             => ':attribute harus dengan format email contoh: agus@gmail.com',
                'numeric'           => ':attribute harus berupa angka',
                'min' => ':attribute minimal 6 karakter',
                'unique'          => ':attribute sudah ada.',
                'regex' => 'Pastikan :attribute tanpa tanda baca.'
            ]
        )->setAttributeNames(
            [
                'name'       => 'Nama',
                'phone'      => 'No. Telp',
                'email'      => 'Email',
                'password'   => 'Kata Sandi',
                'repassword' => 'Konfirmasi Kata Sandi',
            ]
        );


        if ($validator->fails()) {
            return back()->withInput($request->all())->withErrors($validator->errors());
        }
        
        // $data           = new Warehouse();
        // $data->name     = $request->name;
        // $data->email    = $request->email;
        // $data->phone    = $request->phone;
        // $data->password = Hash::make($request->password);
        // $data->status   = 1;
        // $data->store_id = Auth::user()->store->id;
        // $data->save();
        
        return redirect()->route('app.warehouse.index')->with('success', 'Berhasil menambah data');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Warehouse::findOrFail($id);

        return view('backend.warehouse.form', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator       = \Validator::make(
            $request->all(),
            [
                'name'       => 'required|string|regex:/^[0-9A-Za-z_ ]*$/',
                'phone'      => 'required|numeric',
                'email'      => 'required|email|email|unique:warehouse,email'.($id ? ",$id" : '').',id',
                'password'   => 'nullable|string|min:6|confirmed',
            ],
            [
                'confirmed' => ':attribute tidak cocok',
                'required'          => ':attribute tidak boleh kosong.',
                'email'             => ':attribute harus dengan format email contoh: agus@gmail.com',
                'numeric'           => ':attribute harus berupa angka',
                'min' => ':attribute minimal 6 karakter',
                'unique'          => ':attribute sudah ada.',
                'regex' => 'Pastikan :attribute tanpa tanda baca.'
            ]
        )->setAttributeNames(
            [
                'name'       => 'Nama',
                'phone'      => 'No. Telp',
                'email'      => 'Email',
                'password'   => 'Kata Sandi',
                'repassword' => 'Konfirmasi Kata Sandi',
            ]
        );


        if ($validator->fails()) {
            return back()->withInput($request->all())->withErrors($validator->errors());
        }
        
        $data           = Warehouse::findOrFail($id);
        $data->name     = $request->name;
        $data->email    = $request->email;
        $data->phone    = $request->phone;
        $data->status   = 1;
        $data->store_id = Auth::user()->store->id;

        if ($request->password != '') {
            $data->password = Hash::make($request->password);
        }

        $data->save();
        
        return redirect()->route('app.warehouse.index')->with('success', 'Berhasil edit data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Warehouse::findOrFail($id);
        $data->status = -1;
        $data->email = $data->email.uniqid();
        $data->save();

        return redirect()->route('app.warehouse.index')->with('success', 'Berhasil menghapus data');
    }
}

backup_dev_version/app/Http/Controllers/Warehouse/AppController.php
<?php

namespace App\Http\Controllers\Warehouse;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AppController extends Controller
{
    public function index()
    {
        return view('warehouse.home');
    }
}

backup_dev_version/app/Http/Controllers/Warehouse/StockController.php
<?php

namespace App\Http\Controllers\Warehouse;

use App\Models\Order;
use App\Models\Ecommerce\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class StockController extends Controller
{
    public function index()
    {
        $data = Product::where('store_id', Auth::guard('warehouse')->user()->store_id)->where('status', '=', 1)->get();

        return view('warehouse.stock.index', compact('data'));
    }
    public function update(Request $req)
    {
        $data = Product::findOrFail($req->id);

        $data->stock = $req->stock;
        $data->save();
        return redirect()->route('warehouse.stock.index')->with('success', 'Berhasil Edit Data');
    }
}

backup_dev_version/resources/views/warehouse/layouts/app.blade.php
<!doctype html>

<html lang="{{ app()->getLocale() }}">

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1">



    <title>@yield('page-title')</title>



    <link rel="stylesheet" href="/apps/css/normalize.css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <link rel="stylesheet" href="/apps/css/font-awesome.min.css">

    <link rel="stylesheet" href="/apps/css/themify-icons.css">

    <link rel="stylesheet" href="/apps/css/flag-icon.min.css">

    <link rel="stylesheet" href="/apps/css/cs-skin-elastic.css">

    <!-- <link rel="stylesheet" href="assets/css/bootstrap-select.less"> -->

    <link rel="stylesheet" href="/apps/scss/style.css">
    
    <link rel="shortcut icon" href="/landing/img/icon.png" type="image/x-icon">
    <link href="/apps/css/custom.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

    <style type="text/css">

    	html, body {

            max-width: 100%;

            overflow-x: hidden;

        }

        @media screen and (max-width:580px){

            .navbar .navbar-brand img{

                width: 100px;

            }

        }

    </style>



    @stack('head')



</head>

<body>

	        <!-- Left Panel -->


    <aside id="left-panel" class="left-panel">

        <nav class="navbar navbar-expand-sm navbar-default">



            <div class="navbar-header">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">

                    <i class="fa fa-bars"></i>

                </button>

                <a class="navbar-brand" href="{{route('app.dashboard')}}"><img src="https://refeed.id/landing/img/refeed-logo.png?ver=1.2" style="filter: brightness(0) invert(1);" alt="Refeed"></a>

                <a class="navbar-brand hidden" href="{{route('app.dashboard')}}"><img src="https://refeed.id/landing/img/logo-chats.png?ver=1.2" alt="Refeed"></a>


            </div>



            <div id="main-menu" class="main-menu collapse navbar-collapse">

                
                   
                <ul class="nav navbar-nav">

                    <div class="user-details">

                        <div class="pull-left">

                            <img src="" alt="">

                        </div>

                        <div class="user-info">

                            <div class="dropdown">

                                <a href="#">Hi, {{Auth::guard('warehouse')->user()->name}}</a>

                            </div>

                        </div>

                    </div>

                    <h3 class="menu-title">Navigation</h3>

                  

                    

                   
                        <li>

                            <a href="{{route('warehouse.dashboard')}}" > <i class="menu-icon fa fa-dashboard"></i>Dashboard</a>

                        </li>
                        <li class="{{ (request()->is('warehouse/stock*')) ? 'active' : '' }}">
                            <a href="{{ route('warehouse.stock.index') }}"> <i class="menu-icon fa fa-list"></i>Stock</a>
                        </li>
                        
                        <li class="{{ (request()->is('warehouse/sales*')) ? 'active' : '' }}">
                            <a href="{{ route('warehouse.sales.index') }}"> <i class="menu-icon fa fa-shopping-cart"></i>Pesanan
                                {{-- &nbsp;
                                <span class="badge badge-success">0</span> --}}
                            </a>
                        </li>
                        
                </ul>

            </div><!-- /.navbar-collapse -->

        </nav>

    </aside><!-- /#left-panel -->



    <!-- Left Panel -->



    <!-- Right Panel -->

    <div id="right-panel" class="right-panel">



        <!-- Header-->

        <header id="header" class="header">



            <div class="header-menu">



                <div class="col-sm-7">

                    <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>

                </div>



                <div class="col-sm-5">

                    <div class="user-area dropdown float-right">

                        <a style="color:#ffffff;" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                             {{Auth::guard('warehouse')->user()->name}} &nbsp;<i class="fa fa-angle-down"></i>

                        </a>



                        <div class="user-menu dropdown-menu">
                                {{-- <a class="nav-link" href="{{ route('reseller.setting') }}"><i class="fa fa-cog"></i> Pengaturan Akun</a> --}}

                                <a class="nav-link" onclick="event.preventDefault();

                                                     document.getElementById('logout-form').submit();">

                                        <i class="fa fa-power-off"></i> {{ __('Logout') }}</a>

                                <form id="logout-form" action="{{ route('warehouse.logout') }}" method="POST" style="display: none;">

                                        @csrf

                                    </form>

                        </div>

                    </div>



                </div>

            </div>



        </header><!-- /header -->

       
	@yield('content')
        
	<!-- Right Panel -->

	

	@include('reseller.layouts.main_js')



    @stack('scripts')

	

</body>

</html>

backup_dev_version/resources/views/warehouse/layouts/head.blade.php
	<link rel="stylesheet" href="backend/assets/css/normalize.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="backend/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="backend/assets/css/themify-icons.css">
    <link rel="stylesheet" href="backend/assets/css/flag-icon.min.css">
    <link rel="stylesheet" href="backend/assets/css/cs-skin-elastic.css">
    <!-- <link rel="stylesheet" href="assets/css/bootstrap-select.less"> -->
    <link rel="stylesheet" href="backend/assets/scss/style.css">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->

backup_dev_version/resources/views/warehouse/layouts/home.blade.php
@extends('backend.layouts.app')


@section('content')
        <div class="breadcrumbs">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Dashboard</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li class="active">Dashboard</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <div class="content mt-3">

            <div class="col-sm-6 col-lg-4">
                <div class="card text-white bg-flat-color-2">
                    <div class="card-body pb-0">
                        
                        <h4 class="mb-0">
                            <span class="count">10468</span>
                        </h4>
                        <p class="text-light">Penjualan</p>

                        <div class="chart-wrapper px-0" style="height:70px;" height="70"/>
                            <h1><i class="fa fa-shopping-cart"></i></h1>
                        </div>

                    </div>
                </div>
            </div>
            <!--/.col-->

            <div class="col-sm-6 col-lg-4">
                <div class="card text-white bg-flat-color-3">
                    <div class="card-body pb-0">
                        
                        <h4 class="mb-0">
                            <span class="count">10468</span>
                        </h4>
                        <p class="text-light">Pending</p>
                        <div class="chart-wrapper px-0" style="height:70px;" height="70"/>
                            <h1><i class="fa fa-clock-o"></i></h1>
                        </div>
                    </div>

                        
                </div>
            </div>
            <!--/.col-->

            <div class="col-sm-12 col-lg-4">
                <div class="card text-white bg-flat-color-4">
                    <div class="card-body pb-0">
                        
                        <h4 class="mb-0">
                            <span class="count">10468</span>
                        </h4>
                        <p class="text-light">Transaksi</p>

                        <div class="chart-wrapper px-3" style="height:70px;" height="70"/>
                            <h1><i class="fa fa-exchange"></i></h1>
                        </div>

                    </div>
                </div>
            </div>
            <!--/.col-->


        </div> <!-- .content -->
    </div><!-- /#right-panel -->
@endsection

backup_dev_version/resources/views/warehouse/layouts/main_js.blade.php
<script src="/apps/js/vendor/jquery-2.1.4.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

<!-- <script src="assets/js/vendor/jquery-2.1.4.min.js"></script> -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script> -->
<script src="/apps/js/plugins.js"></script>
<script src="/apps/js/main.js"></script>


<script src="/apps/js/lib/chart-js/Chart.bundle.js"></script>
<script src="/apps/js/dashboard.js"></script>
<script src="/apps/js/widgets.js"></script>
<script src="/apps/js/lib/vector-map/jquery.vmap.js"></script>
<script src="/apps/js/lib/vector-map/jquery.vmap.min.js"></script>
<script src="/apps/js/lib/vector-map/jquery.vmap.sampledata.js"></script>
<script src="/apps/js/lib/vector-map/country/jquery.vmap.world.js"></script>


<script type="text/javascript" src="/js/jquery.countdown.js"></script>