routes/web.php
<?php
use Illuminate\Http\Request;
use App\Http\Middleware\Supplier;
use App\Models\Ecommerce\Product;



Route::post('app/ipaymu/notify/cod', 'Ecommerce\SettingController@ipaymuNotify')->name('notify');

Route::post('/ipaymu/notify', 'Store\StoreController@ipaymu');

Route::get('app/api/zipcode', 'Ecommerce\SettingController@getZipCode')->name('app.setting.zipcode');
Route::group(['domain' => 'seller.refeed.co.id', 'namespace' => 'Seller'], function () {
    Route::group(['prefix' => '{seller}'], function () {
        Route::get('/', 'StoreController@index')->name('store');
        Route::get('/product', 'ProductController@index')->name('product');
        Route::get('/product/{slug}', 'ProductController@show')->name('product.show');
        Route::post('/cart', 'CartController@store')->name('cart.store');
        Route::get('/cart', 'CartController@index')->name('cart.index');
        Route::get('/checkout', 'CheckoutController@index')->name('checkout.index');
    });
});

Route::get('totalMembers', function () {
    $total = \App\Models\Ecommerce\Store::count();
    return response()->json(['Members' => $total]);
});

Route::get('/digital/{id}', 'Store\CartController@download')->name('digital');

Route::post('/winpay/payment', 'Store\CartController@notify_winpay');
Route::get('/cron-notify/{id}', 'Store\CartController@cron')->name('cron-notify');

Route::get('/events/{event_id}', 'Events\Event@index');
Route::post('/events/checklimit', 'Events\Event@limitingUsers');
Route::post('/events/create', 'Auth\RegisterController@createPromo');

Route::get('/aws', 'AwsController@index');
Route::post('register-reseller-post', 'ResellerController@register_process')->name('register-reseller-post');
// Route::get('register-reseller', 'ResellerController@register')->name('register-reseller');


//reseller = dropship
//reseller new= reseller

Route::get('register-dropshipper', 'ResellerController@registerDropshipper')->name('register-dropshipper');

Route::post('login-reseller-post', 'ResellerController@login_process')->name('login-reseller-post');
Route::get('login-reseller', 'Auth\AuthController@showLoginReseller')->name('login-reseller');
Route::get('reseller-activation', 'ResellerController@activation')->name('reseller.activation');
Route::post('logout-reseller', 'ResellerController@logout')->name('logout-reseller');
Route::post('reseller/add-cart', 'Reseller\CartController@create');
Route::group(['as' => 'reseller.', 'prefix' => 'dropship', 'namespace' => 'Reseller'], function () {
    Route::group(['middleware' => ['reseller']], function () {
        Route::get('/', 'AppController@index')->name('dashboard');
        Route::post('/setting', 'SettingController@update')->name('setting.update');
        Route::get('/setting', 'SettingController@index')->name('setting');
        Route::get('/panduan', 'DocController@index')->name('panduan');
        Route::get('/pengumuman', 'DocController@pengumuman')->name('pengumuman');
        Route::get('/rule', 'DocController@rule')->name('rule');
        Route::get('/reward', 'DocController@reward')->name('reward');
        Route::get('/faq', 'DocController@faq')->name('faq');
        Route::get('/product', 'ProductController@index')->name('product');
        Route::get('/product/{id}', 'ProductController@show')->name('product.show');
        Route::get('/sales', 'OrderController@index')->name('sales');
        Route::get('/sales/edit/{id}', 'OrderController@edit')->name('sales.edit');

        Route::get('/cart/{session}', 'CartController@index')->name('cart');
        Route::post('/cart/store', 'CartController@store')->name('cart.store');
        Route::post('/delete-cart/{id}', 'CartController@destroy')->name('delete-cart');
        Route::get('/payment/{id}', 'CartController@payment')->name('payment');
    });
});

Route::get('login-warehouse', 'Warehouse\LoginController@login')->name('login-warehouse');
Route::post('login-warehouse', 'Warehouse\LoginController@login_process')->name('login-warehouse-post');

Route::group(['as' => 'warehouse.', 'prefix' => 'warehouse', 'namespace' => 'Warehouse'], function () {
    Route::group(['middleware' => ['warehouse']], function () {
        Route::get('/', 'AppController@index')->name('dashboard');
        
        Route::get('/sales', 'SalesController@index')->name('sales.index');
        Route::get('/sales/edit/{id}', 'SalesController@edit')->name('sales.edit');
        Route::get('/sales/{id}', 'SalesController@show')->name('sales.show');
        Route::post('/sales/update/{id}', 'SalesController@update')->name('sales.update');
        Route::get('/sales/search', 'SalesController@search')->name('sales.search');
        Route::get('/sales/export', 'SalesController@export')->name('sales.export');
        
        Route::get('/stock', 'StockController@index')->name('stock.index');
        Route::post('/stock/update', 'StockController@update')->name('stock.update');
        
        Route::post('logout', 'LoginController@logout')->name('logout');
    });
});


Route::group(['as' => 'affiliasi.', 'prefix' => 'affiliasi', 'namespace' => 'Affiliasi'], function () {

    Route::get('login', 'AccountController@login')->name('login');
    Route::get('/register', 'AccountController@register')->name('register');
    Route::post('register-process', 'AccountController@register_process')->name('register-process');
    Route::post('login', 'AccountController@login_process')->name('login-process');
    Route::get('activation', 'AccountController@activation')->name('activation');
    Route::post('logout', 'AccountController@logout')->name('logout');

    Route::group(['middleware' => ['affiliasi']], function () {
        Route::get('/', 'AppController@index')->name('dashboard');
        // Route::post('/setting','SettingController@update')->name('setting.update');
        // Route::get('/setting', 'SettingController@index')->name('setting');
        // Route::get('/panduan', 'DocController@index')->name('panduan');

        Route::resource('/user', 'UserController', ['names' => 'user']);
        Route::resource('/product', 'ProductController', ['names' => 'product']);
        Route::resource('/fee', 'FeeController', ['names' => 'fee']);
    });
});

Route::group(['domain' => '{subdomain}.refeed.id', 'where' => ['subdomain' => '(?!\\bwww\\b)[0-9A-Za-z\-\_]+']], function () {

    Route::get('login-dropshipper', 'ResellerController@login_dropshipper')->name('login-dropshipper');

    Route::get('register-reseller','ResellerReal\AccountController@register')->name('register.reseller');

    // Route::get('/', 'Store\StoreController@index')->name('store');
    Route::get('/', 'Store\StoreController@indexNew')->name('store');
    Route::get('/beranda', 'Store\StoreController@index')->name('store.beranda');

    Route::get('/product', 'Store\StoreController@product')->name('product');
    Route::get('/product/{slug}', 'Store\StoreController@detailProduct')->name('item');
    Route::get('/cart/{session}', 'Store\CartController@index')->name('cart');
    Route::get('/success/{id}', 'Store\StoreController@success')->name('success');
    Route::post('/notify/{id}', 'Store\StoreController@notify')->name('notify');
    Route::get('/check-transaction', 'Store\StoreController@checkTransaction')->name('checktrx');
    Route::get('/search', 'Store\StoreController@search')->name('search');
    Route::get('/category/{id}', 'Store\StoreController@getCategory')->name('category');
    Route::get('/note', 'Store\StoreController@note')->name('note');

    Route::post('/add-cart', 'Store\CartController@create');
    Route::get('/add-cart123', 'Store\CartController@create');
    Route::post('/delete-cart/{id}', 'Store\CartController@destroy')->name('delete-cart');
    Route::post('/add-order', 'Store\CartController@add_order')->name('add-order');
    Route::post('/add-orderReseller', 'Ecommerce\ResellerReal@add_order')->name('add-orderReseller');

    Route::post('/check', 'Store\StoreController@getcheckTransaction')->name('checkTransaction');
    Route::post('/check-coupon', 'Store\StoreController@checkCoupon')->name('check-coupon');

    Route::get('/toolbar', 'Store\CartController@toolbar')->name('toolbar');
    Route::get('/token', 'Store\CartController@token')->name('token');
    Route::get('/payment', 'Store\CartController@payment')->name('payment');
    Route::get('/payment1', 'Store\CartController@payment1')->name('payment1');
    Route::get('/awb', 'Store\StoreController@awb')->name('awb');
    Route::post('/visitor', 'Store\StoreVisitorController@visitor')->name('visitor');
    Route::get('/page/{id}', 'Store\StoreController@page')->name('page');
    
    Route::post('/create-testimoni', 'Store\StoreController@testimoniCreate')->name('create.testimoni');
    Route::get('/create-testimoni', 'Store\StoreController@testimoniForm')->name('create.testimoni');
    Route::get('/testimoni', 'Store\StoreController@testimoni')->name('testimoni');
    Route::get('/vidio', 'Store\StoreController@vidio')->name('vidio');
});

Route::group(['domain' => '{subdomain}.id', 'where' => ['subdomain' => '(?!\\bwww\\b)[0-9A-Za-z\-\_]+']], function () {

    Route::get('login-dropshipper', 'ResellerController@login_dropshipper')->name('login-dropshipper');

    // Route::get('/', 'Store\StoreController@index')->name('store');
    Route::get('/', 'Store\StoreController@indexNew')->name('store');
    Route::get('/beranda', 'Store\StoreController@index')->name('store.beranda');

    Route::get('/product', 'Store\StoreController@product')->name('product');
    Route::get('/product/{slug}', 'Store\StoreController@detailProduct')->name('item');
    Route::get('/cart/{session}', 'Store\CartController@index')->name('cart');
    Route::get('/success/{id}', 'Store\StoreController@success')->name('success');
    Route::post('/notify/{id}', 'Store\StoreController@notify')->name('notify');
    Route::get('/check-transaction', 'Store\StoreController@checkTransaction')->name('checktrx');

app/Http/Controllers/Ecommerce/ResellerController.php
<?php

namespace App\Http\Controllers\Ecommerce;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Reseller;
use App\Models\Order;
use Auth;
class ResellerController extends Controller
{
    public function index()
    { 
        $models = Reseller::where('store_id', Auth::user()->store->id)->paginate(10);
        $data = Order::where('reseller_id', '!=', '0')->where('store_id', Auth::user()->store->id)->where('status', '!=', Order::STATUS_CANCEL)->where('status', '!=', Order::STATUS_WAITING_PAYMENT)->orderBy('created_at', "DESC")->paginate(20);
        
        return view('backend.reseller.index', compact('models', 'data'));
    }

    public function dropship()
    { 
        $user=Auth::user();
        
        $models = Reseller::where('store_id', Auth::user()->store->id)->paginate(10);
        $data = Order::where('reseller_id', '!=', '0')->where('store_id', Auth::user()->store->id)->where('status', '!=', Order::STATUS_CANCEL)->where('status', '!=', Order::STATUS_WAITING_PAYMENT)->orderBy('created_at', "DESC")->paginate(20);
        
        $titleText=$user->getMeta('titleDropship')['meta_value'];
        $desc=$user->getMeta('deskripsiDropship')['meta_value'];

        
        return view('backend.reseller.index', compact('models', 'data','titleText','desc'));
    }

    public function show($id)
    {
        $data = Order::where('reseller_id', $id)->where('store_id', Auth::user()->store->id)->where('status', '!=', Order::STATUS_CANCEL)->where('status', '!=', Order::STATUS_WAITING_PAYMENT)->orderBy('created_at', "DESC")->paginate(20);
        return view('backend.reseller.detail', compact('data'));  
    }
    public function verify($id)
    {
        $data = Reseller::findOrFail($id);
        $status = 1;
        if(\Request::get('status') == 0){
            $status = 0;
        }
        $data->verify = $status;
        $data->save();

        $models = Reseller::where('store_id', Auth::user()->store->id)->paginate(10);
        $data = Order::where('reseller_id', '!=', '0')->where('store_id', Auth::user()->store->id)->where('status', '!=', Order::STATUS_CANCEL)->where('status', '!=', Order::STATUS_WAITING_PAYMENT)->orderBy('created_at', "DESC")->paginate(20);
        return redirect()->back();
        // return view('backend.reseller.detail', compact('data'));  
    }
}

app/Http/Controllers/Reseller/AppController.php
<?php

namespace App\Http\Controllers\Reseller;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use App\Models\Order;
use Carbon;
use App\Reseller;
class AppController extends Controller
{
    
    public function index()
    {
        $data = Auth::guard('resellers')->user();

        $key=Reseller::where("id",$data->id)->first()->meta("ipaymu_apikey");

        $sales      = Order::where('store_id', $data->id)
                        ->whereDate('created_at', Carbon::now()->format('Y-m-d'))
                        ->where('status', '!=', Order::STATUS_CANCEL)
                        ->where('status', '!=', Order::STATUS_WAITING_PAYMENT)
                        ->where('reseller_id', Auth::guard('resellers')->user()->id)
                        ->sum('total');
        $trx_waiting      = Order::where('store_id',  $data->id)
                        ->whereMonth('created_at', Carbon::now()->month)
                        ->where('status', '!=', Order::STATUS_CANCEL)
                        ->where('status', '!=', Order::STATUS_WAITING_PAYMENT)
                        ->where('reseller_id', Auth::guard('resellers')->user()->id)
                        ->sum('total');
        // $trx_waiting  = Order::where('store_id', Auth::user()->store->id)->where('status','0')->whereMonth('created_at', Carbon::now()->month)->count();
        $trx_total  = Order::where('store_id', $data->id)->where('reseller_id', Auth::guard('resellers')->user()->id)->whereMonth('created_at', Carbon::now()->month)->count();
        
        $sdate = DATE('Y-m-d', strtotime(DATE('Y-m-d')."-6 day"));
        for ($i=0; $i < 7; $i++) { 
            $ndate = DATE('Y-m-d', strtotime($sdate."+".$i." day"));
            $sidate = DATE('d-m-Y', strtotime($sdate."+".$i." day"));
            $date_graph[]   = $sidate;

            $amount_graph[] = Order::where('store_id', $data->id)
            ->whereDate('created_at', $ndate)
            ->where('status', '!=', Order::STATUS_CANCEL)
            ->where('status', '!=', Order::STATUS_WAITING_PAYMENT)
            ->where('reseller_id', Auth::guard('resellers')->user()->id)
            ->sum('total');

            $data_per_bulan = Order::where('store_id', $data->id)
            ->whereDate('created_at', $ndate)
            ->where('status', '!=', Order::STATUS_CANCEL)
            ->where('status', '!=', Order::STATUS_WAITING_PAYMENT)
            ->where('reseller_id', Auth::guard('resellers')->user()->id)
            ->get();

            $total_bonus = 0;
            foreach($data_per_bulan as $item){
                foreach($item->detail as $bonus){
                    if($bonus->reseller_unit == 'harga') {
                        $total_bonus += $bonus->reseller_value*$bonus->qty;
                    }else{
                        $total_bonus += $bonus->total*$bonus->reseller_value/100;
                    }
                }
            }

            $amount_graph_bonus[] = $total_bonus; 

                                                   
        }
        $date_graph =json_encode($date_graph);
        $amount_graph =json_encode($amount_graph);
        $amount_graph_bonus =json_encode($amount_graph_bonus);

        
        $models = Order::where('store_id', $data->id)->where('reseller_id', Auth::guard('resellers')->user()->id)->orderBy('id', 'desc')->paginate(10);

        return view('reseller.home', compact('models','key', 'amount_graph', 'amount_graph_bonus', 'date_graph', 'data', 'trx_total', 'trx_waiting', 'sales'));
    }
}

app/Http/Controllers/Reseller/DocController.php
<?php

namespace App\Http\Controllers\Reseller;

use App\Http\Controllers\Controller;
use App\Models\Guide;
use Illuminate\Http\Request;
use Auth;
use App\Models\Ecommerce\Store;
use App\Models\StoreFaq;

class DocController extends Controller
{
    public function index()
    {
        $me=Auth::guard('resellers')->user();
        
        // $models = Guide::where('target', 'DROPSHIPPER')->whereIn("store_id",$me->store_id)->get();
        $models = Guide::where('target', 'DROPSHIPPER')
            ->where(function ($query) {
                $query->where('store_id',Auth::guard('resellers')->user()->store_id)
                    ->orWhereNull('store_id');
            }
        )->get();
        return view('reseller.panduan.index', compact('models'));
    }
    public function pengumuman()
    {
        $models = Guide::where('target', 'SR')->where('store_id', Auth::guard('resellers')->user()->store->id)->orderBy('id', 'desc')->get();
        return view('reseller.pengumuman.index', compact('models'));
    }
    public function rule()
    {
        $models =  Store::findOrFail(Auth::guard('resellers')->user()->store->id);
        return view('reseller.pengumuman.rule', compact('models'));
    }
    public function reward()
    {
        $models =  Store::findOrFail(Auth::guard('resellers')->user()->store->id);
        return view('reseller.pengumuman.reward', compact('models'));
    }
    public function faq()
    {
        $models =  Store::findOrFail(Auth::guard('resellers')->user()->store->id);
        $datas = StoreFaq::where('status', '=', 1)
                    ->where('store_id', '=', Auth::guard('resellers')->user()->store->id)
                    // ->where('category', '=', 'dropship')
                    ->get();
        return view('reseller.pengumuman.faq', compact('models', 'datas'));
    }
}

resources/views/reseller/order/index.blade.php
@extends('reseller.layouts.app')
@section('page-title','Bonus Penjualan')

@section('content')
<div class="breadcrumbs">
        <div class="col-sm-4">
            <div class="page-header float-left">
                <div class="page-title">
                    <h1>Bonus Penjualan</h1>
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="page-header float-right">
                <div class="page-title">
                        
                </div>
            </div>
        </div>
    </div>

    <div class="content mt-3">
            <div class="animated">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title">Daftar Bonus Penjualan</strong>
                            </div>
                            <div class="card-body">
                                <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                    <thead>
                                    <tr>
                                        <th width="100">#</th>
                                        <th>Invoice</th>
                                        <th>Tanggal Transaksi</th>
                                        <th>Status Transaksi</th>
                                        <th>Bonus</th>
                                        <th>Status Bonus</th>
                                        <th>Opsi</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @if($models->count() == 0)
                                        <tr>
                                            <td colspan="7"><i>Tidak ada data ditampilkan</i></td>
                                        </tr>
                                    @endif
                                    @foreach($models as $key => $item)
                                    <tr>
                                            <td>{{ ($models->perPage() * ($models->currentPage() - 1)) + ($key + 1) }}</td>
                                            <td>{{ $item->invoice() }}</td>
                                            <td>{{ \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $item->created_at)->format('d-m-Y') }}</td>
                                            <td>
                                                    <span class="badge badge-{{ $item->get_label()->color }}">{{ $item->get_label()->label }}</span>
                                            </td>
                                            <td>
                                                    @php($total_bonus = 0)
                                                    @foreach($item->detail as $bonus)
                                                    @if($bonus->reseller_unit == 'harga')
                                                        @php($total_bonus += $bonus->reseller_value*$bonus->qty)
                                                    @else
                                                        @php($total_bonus += $bonus->total*$bonus->reseller_value/100)
                                                    @endif
                                                    @endforeach
                                                    {{'Rp '.number_format($total_bonus)}}
                                                </td>
                                            <td>
                                                @if(($item->meta('reseller_pay') == '1') && ($item->status > 0))
                                                    Sudah Ditransfer
                                                @elseif($item->status > 0)
                                                    Pending
                                                @else
                                                    Belum
                                                @endif
                                            </td>
                                            <td>
                                                    <a href="{{ route('reseller.sales.edit', $item->id) }}" class="btn btn-sm btn-success">Detail</a>
                                                </td>
                                            
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
    
                                {{ $models->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- .animated -->
        </div><!-- .content -->
@endsection